Dev
ysimakina/ugmk_test_app pull request #1
Opened 2024-10-29 09:31 UTC by ysimakina

Completed all the tasks for the project ugmk_test_app.

2024-10-29 12:46 UTC, vkarelina commented on backend/src/products/products.controller.ts
> +    async getFactoryData(@Res() res: Response) {
Почему res?

2024-10-29 12:49 UTC, vkarelina commented on backend/src/products/products.service.ts
> +interface Data {
interface можно вынести в types.ts

2024-10-29 12:50 UTC, vkarelina commented on backend/src/products/products.service.ts
> +    return products.products;
products.products?

2024-10-29 12:51 UTC, vkarelina commented on backend/src/products/products.service.ts
> +    let product1Total = 0;
А есть продуктов 100? Может лучше массивом хранить?

2024-10-29 12:52 UTC, vkarelina commented on frontend/src/pages/DetailChart/DetailChart.tsx
> +import { months } from '../../../constants';
Пробела нет между импортами

2024-10-29 13:18 UTC, vkarelina commented on backend/src/products/products.controller.ts
>          @Param('factoryId') factoryId: number,
parseIntPipe

2024-10-29 13:23 UTC, vkarelina commented on backend/Dockerfile
> +RUN npm run build
Зачем тут build?

2024-10-29 13:24 UTC, vkarelina commented on backend/Dockerfile
> +FROM node:18
18? Почему не alpine?

2024-10-29 13:28 UTC, vkarelina commented on frontend/nginx.conf
> +}
Пустая строка

2024-10-29 13:34 UTC, vkarelina commented on frontend/nginx.conf
> +}
без events {} запускается?

2024-10-29 13:42 UTC, vkarelina commented on frontend/src/pages/MonthlyProductionChart/MonthlyProductionChart.tsx
> +  const [data, setData] = useState<FactoryData[]>([]);
Общие названия

2024-10-30 08:12 UTC, s-skubedin requested changes

2024-10-30 08:12 UTC, s-skubedin commented on backend/Dockerfile
> +FROM node:18
Это не принципиально
alpine - ОС

2024-10-30 08:12 UTC, s-skubedin commented on backend/Dockerfile
> +RUN npm run build
Этот докер для прод режима

2024-10-30 08:12 UTC, s-skubedin commented on backend/src/products/products.controller.ts
> +    async getFactoryData(@Res() res: Response) {
Что с ним?

2024-10-30 08:12 UTC, s-skubedin commented on backend/src/products/products.controller.ts
> +    async getFactoryData(@Res() res: Response) {
passthrough

2024-10-30 08:12 UTC, s-skubedin commented on frontend/package.json
> +    "recharts": "^2.13.0"
Как-то много charts, все либы используешь?

2024-10-30 08:12 UTC, s-skubedin commented on frontend/package.json
> +    "papaparse": "^5.4.1",
Зачем это?

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/App.tsx
> +import DetailChart from './pages/DetailChart/DetailChart';
sort

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/App.tsx
> +export default App;
Пустая строка перед

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/pages/DetailChart/DetailChart.tsx
> +    };
fetch должен быть в отдельной папке api

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/pages/DetailChart/DetailChart.tsx
> +    fetchData();
fetchData().then(setData)

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/pages/DetailChart/DetailChart.tsx
> +  ];
Вынеси за компонент

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/pages/DetailChart/DetailChart.tsx
> +        Статистика по продукции фабрики {Number(factoryId) === 1 ? 'A' : 'B'} в
factoryId === '1'

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/pages/MonthlyProductionChart/MonthlyProductionChart.tsx
> +      if (isNaN(monthIndex)) return;
Number.isFinite - безопасней

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/pages/MonthlyProductionChart/MonthlyProductionChart.tsx
> +      }
Дублирование кода
Код не рассчитан на рост продуктов

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/pages/MonthlyProductionChart/MonthlyProductionChart.tsx
> +          value={localStorage.getItem('filter') ?? filter}
'filter' - магическая строка. Должна быть в константе
операции с LS - необходимо вынести в утилиты. Стоит мемоизировать получение данных из LS. Чтобы не грузить на каждый рендер

2024-10-30 08:12 UTC, s-skubedin commented on frontend/src/pages/MonthlyProductionChart/MonthlyProductionChart.tsx
> +          dataKey="factoryB"
Разбей на компоненты

2024-10-30 14:59 UTC, s-skubedin approved these changes

2024-10-30 15:18 UTC, vkarelina approved these changes

2024-10-31 06:50 UTC, merged